### ISSUE TITLE
prop assets

### ISSUE THREAD

**Issue by selfsame** [selfsame/procadia2016#4]
dozen or so props you would expect to find in/around a skatepark

some suggestions

- [x] park bench
- [x] light pole
- [x] power lines
- [x] garbage can
- [x] fence segment
- [x] boom box

**Comment by Polyrhythm** [comment]
`captain's log, stardate 123123082`: i spent way too long on the damn boombox 📻 
https://github.com/selfsame/procadia2016/commit/e8e9a0f80f21fceabbdad7a519a7904bc4350b41

**Comment by Polyrhythm** [comment]
https://github.com/selfsame/procadia2016/commit/ee514fb00761f987eba6ad2e45458bbba0564c6a
